import { describe, it, expect, vi, beforeAll, afterEach } from 'vitest';
import { resolve } from 'path';
import { pathToFileURL } from 'url';
import * as pdfjsLib from 'pdfjs-dist';
import { jsPDF } from '../lib/jspdf.js';
import { PdfEngine } from '../engine/pdf-engine.js';

/**
 * Two layers of coverage:
 *
 *  - extractPdfText never touches a canvas, so it runs against real pdf.js with
 *    fixtures generated by jsPDF (already a dependency). That is a genuine
 *    round-trip: write a PDF, read it back, compare the text.
 *
 *  - renderPdfToImages does rasterise, and jsdom has no canvas backend, so pdf.js
 *    is swapped for a stub. What is under test there is PdfEngine's own
 *    orchestration — page iteration, viewport scale, mime routing and filename
 *    derivation — not pdf.js's rendering.
 */

/** Builds a real PDF File whose pages carry the given lines of text. */
function pdfFixture(pages, name = 'fixture.pdf') {
  const doc = new jsPDF();
  pages.forEach((lines, index) => {
    if (index > 0) doc.addPage();
    [].concat(lines).forEach((line, lineIndex) => {
      if (line) doc.text(line, 15, 20 + lineIndex * 10);
    });
  });

  const buffer = doc.output('arraybuffer');
  const file = new File([buffer], name, { type: 'application/pdf' });
  // jsdom's File does not implement arrayBuffer() in every version.
  if (typeof file.arrayBuffer !== 'function') {
    file.arrayBuffer = async () => buffer;
  }
  return file;
}

beforeAll(() => {
  // pdf-engine.js points workerSrc at `new URL('pdfjs-dist/build/pdf.worker.mjs',
  // import.meta.url)`. Vite rewrites that to the emitted asset at build time (the
  // build really does produce dist/assets/pdf.worker-*.mjs), but vitest leaves the
  // bare specifier alone, so it resolves against the dev server origin and the ESM
  // loader rejects the resulting http:// URL. Point it at the on-disk worker so the
  // fixtures are parsed by the same pdf.js that ships in the extension.
  pdfjsLib.GlobalWorkerOptions.workerSrc = pathToFileURL(
    resolve('node_modules/pdfjs-dist/build/pdf.worker.mjs')
  ).href;
});

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
});

describe('PdfEngine.extractPdfText (real pdf.js round-trip)', () => {
  it('reads back the text written into a single-page PDF', async () => {
    const file = pdfFixture([['Universal File Converter']]);
    const text = await PdfEngine.extractPdfText(file);

    expect(text).toContain('Universal File Converter');
  });

  it('labels every page and keeps them in order', async () => {
    const file = pdfFixture([['Alpha page one'], ['Bravo page two'], ['Charlie page three']]);
    const text = await PdfEngine.extractPdfText(file);

    expect(text).toContain('--- Page 1 ---');
    expect(text).toContain('--- Page 2 ---');
    expect(text).toContain('--- Page 3 ---');
    expect(text.indexOf('Alpha')).toBeLessThan(text.indexOf('Bravo'));
    expect(text.indexOf('Bravo')).toBeLessThan(text.indexOf('Charlie'));
  });

  it('joins multiple text runs on the same page with spaces', async () => {
    const file = pdfFixture([['First line here', 'Second line here']]);
    const text = await PdfEngine.extractPdfText(file);

    expect(text).toMatch(/First line here\s+Second line here/);
  });

  it('still emits a page marker for a page with no text', async () => {
    const file = pdfFixture([['Only page one has text'], ['']]);
    const text = await PdfEngine.extractPdfText(file);

    expect(text).toContain('--- Page 2 ---');
  });

  it('returns trimmed output with no trailing blank lines', async () => {
    const file = pdfFixture([['Trailing whitespace check']]);
    const text = await PdfEngine.extractPdfText(file);

    expect(text).toBe(text.trim());
    expect(text.endsWith('\n')).toBe(false);
  });

  it('rejects a file that is not a PDF', async () => {
    const notPdf = new File(['this is plain text, not a pdf'], 'notes.txt', { type: 'text/plain' });
    notPdf.arrayBuffer = async () => new TextEncoder().encode('this is plain text, not a pdf').buffer;

    await expect(PdfEngine.extractPdfText(notPdf)).rejects.toThrow();
  });
});

describe('PdfEngine.renderPdfToImages (pdf.js stubbed)', () => {
  /**
   * Loads a fresh PdfEngine wired to a stubbed pdf.js and canvas, and reports
   * what the engine asked for along the way.
   */
  async function withStubbedPdfjs({ numPages = 1 } = {}) {
    const renderCalls = [];
    const viewportCalls = [];
    const canvases = [];

    vi.resetModules();
    vi.doMock('pdfjs-dist', () => ({
      GlobalWorkerOptions: {},
      getDocument: vi.fn(() => ({
        promise: Promise.resolve({
          numPages,
          getPage: vi.fn(async (pageNumber) => ({
            pageNumber,
            getViewport: vi.fn((options) => {
              viewportCalls.push(options);
              return { width: 200 * options.scale, height: 100 * options.scale };
            }),
            render: vi.fn((options) => {
              renderCalls.push(options);
              return { promise: Promise.resolve() };
            })
          }))
        })
      }))
    }));

    const originalCreateElement = document.createElement.bind(document);
    vi.spyOn(document, 'createElement').mockImplementation((tag) => {
      if (tag !== 'canvas') return originalCreateElement(tag);
      const canvas = {
        width: 0,
        height: 0,
        getContext: () => ({ id: 'ctx' }),
        toDataURL: vi.fn((mime) => `data:${mime};base64,AAAA`)
      };
      canvases.push(canvas);
      return canvas;
    });

    // renderPdfToImages turns each data URL back into a Blob via fetch().
    vi.stubGlobal(
      'fetch',
      vi.fn(async (url) => ({
        blob: async () => new Blob([String(url)], { type: String(url).slice(5).split(';')[0] })
      }))
    );

    const { PdfEngine: Engine } = await import('../engine/pdf-engine.js');
    const file = { name: 'report.pdf', arrayBuffer: async () => new ArrayBuffer(8) };
    return { Engine, file, renderCalls, viewportCalls, canvases };
  }

  afterEach(() => {
    vi.doUnmock('pdfjs-dist');
  });

  it('renders one image per page and numbers them from 1', async () => {
    const { Engine, file } = await withStubbedPdfjs({ numPages: 3 });
    const pages = await Engine.renderPdfToImages(file);

    expect(pages).toHaveLength(3);
    expect(pages.map((p) => p.pageNumber)).toEqual([1, 2, 3]);
  });

  it('derives page filenames from the source name without doubling the extension', async () => {
    const { Engine, file } = await withStubbedPdfjs({ numPages: 2 });
    const pages = await Engine.renderPdfToImages(file, { format: 'png' });

    expect(pages.map((p) => p.filename)).toEqual(['report_page_1.png', 'report_page_2.png']);
  });

  it('defaults to 1.5x scale and sizes the canvas to the viewport', async () => {
    const { Engine, file, viewportCalls, canvases } = await withStubbedPdfjs({ numPages: 1 });
    await Engine.renderPdfToImages(file);

    expect(viewportCalls[0]).toEqual({ scale: 1.5 });
    expect(canvases[0].width).toBe(300); // 200 * 1.5
    expect(canvases[0].height).toBe(150); // 100 * 1.5
  });

  it('honours a caller-supplied scale', async () => {
    const { Engine, file, viewportCalls, canvases } = await withStubbedPdfjs({ numPages: 1 });
    await Engine.renderPdfToImages(file, { scale: 3 });

    expect(viewportCalls[0]).toEqual({ scale: 3 });
    expect(canvases[0].width).toBe(600);
  });

  it('passes the canvas context and viewport through to pdf.js render', async () => {
    const { Engine, file, renderCalls } = await withStubbedPdfjs({ numPages: 1 });
    await Engine.renderPdfToImages(file);

    expect(renderCalls[0].canvasContext).toEqual({ id: 'ctx' });
    expect(renderCalls[0].viewport).toMatchObject({ width: 300, height: 150 });
  });

  it('encodes JPEG when asked and PNG otherwise', async () => {
    const jpg = await withStubbedPdfjs({ numPages: 1 });
    const jpgPages = await jpg.Engine.renderPdfToImages(jpg.file, { format: 'jpg' });
    expect(jpg.canvases[0].toDataURL).toHaveBeenCalledWith('image/jpeg', 0.92);
    expect(jpgPages[0].filename).toBe('report_page_1.jpg');

    const png = await withStubbedPdfjs({ numPages: 1 });
    await png.Engine.renderPdfToImages(png.file, { format: 'png' });
    expect(png.canvases[0].toDataURL).toHaveBeenCalledWith('image/png', 0.92);
  });

  it('returns a blob alongside the data URL for every page', async () => {
    const { Engine, file } = await withStubbedPdfjs({ numPages: 2 });
    const pages = await Engine.renderPdfToImages(file);

    for (const page of pages) {
      expect(page.dataUrl).toMatch(/^data:image\/png;base64,/);
      expect(page.blob).toBeInstanceOf(Blob);
      expect(page.blob.size).toBeGreaterThan(0);
    }
  });
});
